apiVersion: batch/v1
kind: Job
metadata:
  name: cyclonus
  namespace: kube-system
  labels:
    app: cyclonus
spec:
  template:
    spec:
      restartPolicy: Never
      containers:
        - command:
            - ./cyclonus
            - generate
            - --noisy=true
            - --ignore-loopback=true
            - --cleanup-namespaces=true
            - --perturbation-wait-seconds=5
            - --pod-creation-timeout-seconds=30
            - --job-timeout-seconds=2
            - --server-protocol=TCP,UDP
            - --verbosity=debug
            - --exclude=sctp
            - --include=multi-peer
          name: cyclonus
          imagePullPolicy: IfNotPresent
          image: mfenwick100/cyclonus:v0.4.7
      serviceAccount: cyclonus
