apiVersion: apps/v1
kind: Deployment
metadata:
  name: busybox-deployment
  namespace: test1replace
  labels:
    app: busybox
spec:
  replicas: 1000
  selector:
    matchLabels:
      app: busybox
  template:
    metadata:
      labels:
        app: busybox
    spec:
      containers:
        - name: busybox
          image: busybox:latest
          imagePullPolicy: IfNotPresent
          command:
            - sleep
            - "36000"
